# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2e175aad9612814ab91389c6903c9191818f23ff51369d7d76940499371517416f68e2183dd4f8fa8dfb1cf24a4e128984429d6637eeb809a6eacdcda376942

test:
  secret_key_base: c12e555dc738249207bc728edc0a4a42d0025b34dd5007fb127ecc863c5eff506e860cb9860936eb5a83cc6a349d7f2ca3c3ae34c1ab3219d14bdf221a4bfe4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
